### ISSUE TITLE
you can add this to your database

### ISSUE THREAD

**Issue by noahholley** [ryosan-470/factordb-pycli#1]
https://books.google.com/books?id=7Zs9BQAAQBAJ&pg=PA365&lpg=PA365&dq=factoring+n%3D1199+result&source=bl&ots=PoVyXkUl_-&sig=fBP0j04FYgS8LMPt6-CP00YpXo0&hl=en&sa=X&ved=0ahUKEwjks9zJ-LDTAhUY2mMKHSXmAiUQ6AEIIzAA#v=onepage&q=factoring%20n%3D1199%20result&f=false

these have been factored as well:

https://en.wikipedia.org/wiki/Integer_factorization_records

**Comment by ryosan-470** [comment]
I'm sorry I cannot understand what you say. Please explain what you think or contribute my repository is very welcome. 😆

Thank you

**Comment by noahholley** [comment]
sorry my mistake these are in there for some reason i was having an issue accessing the database from cli with whole integers ie not in algebraic form.

**Comment by ryosan-470** [comment]
Thank you for submitting your issue.
