### ISSUE TITLE
How to use FactorDB

### ISSUE THREAD

**Issue by francesco1119** [ryosan-470/factordb-pycli#8]
I have success fully installed FactorDB following your instruction and if I type `factordb 16` in a terminal I receive `2 2 2 2`.
Now I would like to use your code in a .py file so I write my code: 

```
from factordb.factordb import FactorDB

f = FactorDB(16)
print (f)
```

But what I receive as a result is: 

`<factordb.factordb.FactorDB object at 0x7f4961b5dcf8>`

Where am I wrong?

**Comment by ryosan-470** [comment]
Hi @francesco1119 !

You should use `f.connect()` before receiving results so that you write like this:

```python
from factordb.factordb import FactorDB

f = FactorDB(16)
f.connect()
f.get_factor_list()
```

You can use 3 methods available. Ref: https://github.com/ryosan-470/factordb-pycli/blob/3e7bc734a295d4ccdc5e0be810da8a2c183c67e6/factordb/factordb.py#L26-L45

(Sorry, I don't write some documents.)

**Comment by francesco1119** [comment]
I tried: 

```
from factordb.factordb import FactorDB

f = FactorDB(16)
f.connect()
f.get_factor_list()
print (f)
```

returns:

`<factordb.factordb.FactorDB instance at 0x1108a90e0>`

Still cannot understand

**Comment by ryosan-470** [comment]
oh, really?

I'll try to investigate this issue. plz wait for a moment!

**Comment by ryosan-470** [comment]
Hi @francesco1119 

`f.get_factor_list()` is returned by list and this is the value that you want to.
So if you want to use the result, you should write some programs like this:

```python
from factordb.factordb import FactorDB

f = FactorDB(16)
f.connect()
result = f.get_factor_list()
print(result)
```


FYI: https://docs.python.org//3/tutorial/classes.html#instance-objects

**Comment by ryosan-470** [comment]
Hi @francesco1119 

Do you resolve this issue? I closed this issue because you don't reply to this thread. If you have some problems or discussions, please reopen this issue.

Thanks
